version: '3'
services:
  db-service:
    image: mysql:8.0
    container_name: db-nestjs
    restart: always
    environment:
      - MYSQL_DATABASE=cdptw1_groupd
      - MYSQL_ROOT_PASSWORD=groupd
      - MYSQL_ALLOW_EMPTY_PASSWOR=ok
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbuser
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - groupd
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend-service:
    container_name: docker-nestjs
    build:
      context: ./backend
    depends_on:
      - db-service
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
      DB_HOST: db-nestjs
      DB_PORT: 3306
      DB_USER: dbuser
      DB_PASSWORD: dbuser
      DB_NAME: cdptw1_groupd
    links:
      - db-service
    networks:
      - groupd
    volumes:
      - ./backend/src:/usr/src/app/backend/src
      - /usr/src/app/backend/node_modules
  frontend-service:
    container_name: docker-react-app
    build:
      context: ./frontend
    ports:
      - 3001:3000
    networks:
      - groupd
    depends_on:
      - backend-service
    volumes:
      - ./frontend/src:/usr/src/app/frontend/src
      - /usr/src/app/frontend/node_modules
networks:
  groupd:
volumes:
  db:
    driver: local