version: '3'
services:
  backend-service:
    container_name: docker-nestjs
    build:
      context: ./backend
    ports:
      - 5001:8080
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
  frontend-service:
    container_name: docker-react-app
    build:
      context: ./frontend
    ports:
      - 3001:3000
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
