version: '3'
services:
  db-service:
    image: mysql:8.0
    container_name: db-nestjs
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWOR=ok
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - groupd
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend-service:
    container_name: docker-nestjs
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    depends_on:
      - db-service
    ports:
      - 8080:8080
    environment:
      DB_HOST: db-nestjs
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    env_file:
      - .env
    networks:
      - groupd
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
  frontend-service:
    container_name: docker-react-app
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    ports:
      - 3001:3000
    environment:
      REACT_APP_API_URL: http://host.docker.internal:8080
    networks:
      - groupd
    depends_on:
      - backend-service
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
networks:
  groupd:
volumes:
  db:
    driver: local
