FROM node:16-alpine
RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      harfbuzz \
      ca-certificates \
      ttf-freefont \
      nodejs \
      npm

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

#App directory
WORKDIR /usr/src/app/backend

COPY package*.json ./
#Copy all from current directory to App directorys
COPY . .

RUN npm install
RUN npm  i -g @nestjs/cli

CMD ["npm","run","start:dev"]